-- SQL Migration Script for Supabase (PostgreSQL)

-- 1. Create ENUM for Series Status
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'series_status') THEN
        CREATE TYPE series_status AS ENUM ('Watching', 'Watched', 'Plan to Watch');
    END IF;
END $$;

-- 2. Create "Genres" Table
CREATE TABLE IF NOT EXISTS "Genres" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create "Series" Table
CREATE TABLE IF NOT EXISTS "Series" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL,
    "posterUrl" TEXT DEFAULT 'https://via.placeholder.com/300x450?text=No+Poster',
    "status" series_status NOT NULL DEFAULT 'Plan to Watch',
    "GenreId" BIGINT REFERENCES "Genres"("id") ON DELETE SET NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Enable Row Level Security (RLS) - Optional but recommended for Supabase
ALTER TABLE "Genres" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Series" ENABLE ROW LEVEL SECURITY;

-- 5. Create basic policies (Allow all for anonymous for now, consistent with development)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Genres') THEN
        CREATE POLICY "Public Access Genres" ON "Genres" FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Series') THEN
        CREATE POLICY "Public Access Series" ON "Series" FOR ALL USING (true);
    END IF;
END $$;

-- 6. Trigger for updatedAt (PostgreSQL standard approach)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_genres_updated_at ON "Genres";
CREATE TRIGGER update_genres_updated_at BEFORE UPDATE ON "Genres" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_series_updated_at ON "Series";

-- 7. Add type and season columns to the Series table
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'media_type') THEN
        CREATE TYPE media_type AS ENUM ('Serie', 'Pelicula');
    END IF;
END $$;

ALTER TABLE "Series" ADD COLUMN IF NOT EXISTS "type" media_type NOT NULL DEFAULT 'Serie';
ALTER TABLE "Series" ADD COLUMN IF NOT EXISTS "season" INTEGER;
ALTER TABLE "Series" ADD COLUMN IF NOT EXISTS "ratingEmil" DECIMAL(3,2) DEFAULT 0;
ALTER TABLE "Series" ADD COLUMN IF NOT EXISTS "ratingDeli" DECIMAL(3,2) DEFAULT 0;
ALTER TABLE "Series" ADD COLUMN IF NOT EXISTS "ratingAverage" DECIMAL(3,2) DEFAULT 0;
